Added an check if database already exists

diff --git a/bin/v-import-directadmin b/bin/v-import-directadmin
--- a/bin/v-import-directadmin
+++ b/bin/v-import-directadmin
@@ -145,54 +145,61 @@ function run_da_db() {
 		# Substring expresion -5: substring expression < 0
 		# userdb=$(echo $da_db_u |sed "s/.conf//")
 		database_name=${da_db::-5}
-		if [ -e "backup/${database_name}.sql" ]; then
+		grep -w $database_name server_dbs
+		if [ $? == "1" ]; then
+			if [ -e "backup/${database_name}.sql" ]; then
 
-			#Get the database name
-			db=$(grep db_collation backup/${da_db} | tr '&' '\n ' | grep SCHEMA_NAME | cut -d "=" -f 2)
+				#Get the database name
+				db=$(grep db_collation backup/${da_db} | tr '&' '\n ' | grep SCHEMA_NAME | cut -d "=" -f 2)
 
-			tput setaf 2
-			echo " Create and restore ${db} "
+				tput setaf 2
+				echo " Create and restore ${db} "
+				tput sgr0
+				mysql -e "CREATE DATABASE $db"
+				mysql ${db} <backup/${db}.sql
+				#Get all the users of the database
+				while IFS= read -r line;
+				do
+
+					selectdb_line=$( echo $line | grep passwd );
+					if [ ! -z "$selectdb_line" ]; then
+
+						db_user=$(echo $selectdb_line | tr '&' '\n ' | grep ${directadmin_user} | cut -d "=" -f 1)
+						md5=$(echo $selectdb_line | tr '&' '\n ' | grep passwd | cut -d "=" -f 2)
+						
+						echo "DB: $db"
+						echo "udb: $db_user"
+						echo "Password: ${md5}"
+
+						echo "DB='$db' DBUSER='$db_user' MD5='$md5' HOST='localhost' TYPE='mysql' CHARSET='UTF8' U_DISK='0' SUSPENDED='no' TIME='$time' DATE='$data'" >> /usr/local/hestia/data/users/$directadmin_user/db.conf
+					fi
+
+				done < "backup/${da_db}"
+
+				# Leave hestia restore passwords and create users
+				tput setaf 2
+				echo "Rebuild databases files for $directadmin_user"
+				tput sgr0
+				$BIN/v-rebuild-databases $directadmin_user
+
+				
+				# grep -w $db server_dbs
+				# if [ $? == "1" ]; then
+				# 	tput setaf 2
+				# 	echo " Create and restore ${db} "
+				# 	tput sgr0
+				# 	mysql -e "CREATE DATABASE $db"
+				# 	mysql ${db} <backup/${db}.sql
+				# 	echo "Add $db to vestacp"
+				# 	echo "DB='$db' DBUSER='$userdb' MD5='$md5' HOST='localhost' TYPE='mysql' CHARSET='UTF8' U_DISK='0' SUSPENDED='no' TIME='$TIME' DATE='$DATE'" >>/usr/local/vesta/data/users/${directadmin_user}/db.conf
+				# else
+				# 	echo "Error: Cant restore database $db alredy exists in mysql server"
+				# fi
+			fi
+		else
+			tput setaf 1
+			echo "Error: Cant restore database $db alredy exists in mysql server"
 			tput sgr0
-			mysql -e "CREATE DATABASE $db"
-			mysql ${db} <backup/${db}.sql
-			#Get all the users of the database
-			while IFS= read -r line;
-			do
-
-				selectdb_line=$( echo $line | grep passwd );
-				if [ ! -z "$selectdb_line" ]; then
-
-					db_user=$(echo $selectdb_line | tr '&' '\n ' | grep ${directadmin_user} | cut -d "=" -f 1)
-					md5=$(echo $selectdb_line | tr '&' '\n ' | grep passwd | cut -d "=" -f 2)
-					
-					echo "DB: $db"
-					echo "udb: $db_user"
-					echo "Password: ${md5}"
-
-					echo "DB='$db' DBUSER='$db_user' MD5='$md5' HOST='localhost' TYPE='mysql' CHARSET='UTF8' U_DISK='0' SUSPENDED='no' TIME='$time' DATE='$data'" >> /usr/local/hestia/data/users/$directadmin_user/db.conf
-				fi
-
-			done < "backup/${da_db}"
-
-			# Leave hestia restore passwords and create users
-			tput setaf 2
-			echo "Rebuild databases files for $directadmin_user"
-			tput sgr0
-			$BIN/v-rebuild-databases $directadmin_user
-
-			
-			# grep -w $db server_dbs
-			# if [ $? == "1" ]; then
-			# 	tput setaf 2
-			# 	echo " Create and restore ${db} "
-			# 	tput sgr0
-			# 	mysql -e "CREATE DATABASE $db"
-			# 	mysql ${db} <backup/${db}.sql
-			# 	echo "Add $db to vestacp"
-			# 	echo "DB='$db' DBUSER='$userdb' MD5='$md5' HOST='localhost' TYPE='mysql' CHARSET='UTF8' U_DISK='0' SUSPENDED='no' TIME='$TIME' DATE='$DATE'" >>/usr/local/vesta/data/users/${directadmin_user}/db.conf
-			# else
-			# 	echo "Error: Cant restore database $db alredy exists in mysql server"
-			# fi
 		fi
 	done
 }
